fix health_probe and add sticker
IMEsec-USP/ada pull request #15
Opened 2020-09-11 04:13 UTC by r0zbot

2020-09-11 04:45 UTC, AndrewIjano approved these changes
I’m not sure if it works but it lgtm

2020-09-11 08:54 UTC, pedro823 requested changes
Blocking just so that you dont merge without seeing this

2020-09-11 08:54 UTC, pedro823 commented on health_probe.py
> +    start_health_check(logger, backup_handler, {'Ada': ADA_URL}, HEALTHCHECK_SLEEP_AMOUNT, HEALTHCHECK_ANOMALY_THRESHOLD)
Since you're passing the logger around, might as well pass the logger to the `BackupHandler` above, and log instead of `print`.

2020-09-11 08:54 UTC, pedro823 commented on utils/telegram.py
> +                if sticker: bot.send_sticker(chat_id=conversation, text=chunk, sticker=sticker)
1. Does this send `text=chunk` again? Or is this an ignored parameter?
2. This is inside a loop of chunks. If you ask Ada to send a message bigger than 1024 characters, she will repeatedly send the sticker in between the messages. This should be in an outer loop of its own, or you should switch the `for`s around.

2020-09-11 22:42 UTC, pedro823 commented on utils/telegram.py
> +            for chunk in self.chunks(message):
just FYI, you create `n` string separations over here where n is the amount of conversations

2020-09-11 22:42 UTC, pedro823 commented on health_probe.py
>      backup_handler = BackupHandler(handler)
yo u didnt fix this >:(

```python3
backup_handler = BackupHandler(logger, handler)

# and then change print() to logger.log() on broadcast
```

2020-09-12 09:03 UTC, pedro823 approved these changes
LGTM

2020-09-21 15:36 UTC, merged